### PR TITLE
Support for longer sessions and sorted output

### PR DESCRIPTION
**Pull request by dsmk**
The primary reason for this update is to get rid of the 1hr command line session duration.  This code was the only thing keeping the 1 hour duration as the IAM roles already had a longer max session duration and earlier this summer Shibboleth started requesting a longer session duration.  

At the same time I've sorted the roles - some of us have over 20 so the unsorted list is not useful.

I also did a few other minor tweaks either to simplify development with VScode's Python debugger or to clean up output.

### CODE REVIEW

**Comment by bfenster** [comment]
This makes sense to me superficially. It still doesn't let me login, but it's not any worse than the old one in that regard, and the old one lets other (non-me) people login all the time. We've discussed the approach to finding a workable session length before and that looks perfectly viable to me.

**Comment by dsmk** [comment]
> It still doesn't let me login, but it's not any worse than the old one in that regard, and the old one lets other (non-me) people login all the time. 

Is your issue with the old one related to Duo?  If so, what sort of Duo configuration do you have (app, multiple phones, call, and/or text?)

**Comment by bfenster** [comment]
> > It still doesn't let me login, but it's not any worse than the old one in that regard, and the old one lets other (non-me) people login all the time.
> 
> Is your issue with the old one related to Duo? If so, what sort of Duo configuration do you have (app, multiple phones, call, and/or text?)

I don't think so, no. I do consistently get a Duo push (my default delivery method on my one phone) and the error doesn't show up until I acknowledge that push. All of the "wait for Duo to be finished" logic seems to be working as expected. I just tried answering really quickly and waiting a long time, and in both cases shib-auth waits for my Duo response and then immediately returns its standard error:

Unidentified error, check screenshot. Error message: Execution context was destroyed, most likely because of a navigation.

(The screenshot is completely blank: a solid white rectangle.)

**Comment by dsmk** [comment]
Ben,

Is this using the docker image on your developer system?  Have you tried using the awscliaccess/awslogin on ist-aws-toolbox.bu.edu?

**Comment by bfenster** [comment]
> Ben,
> 
> Is this using the docker image on your developer system? Have you tried using the awscliaccess/awslogin on ist-aws-toolbox.bu.edu?

It's actually working right now on ist-aws-toolbox (although my vague memory is that it wasn't working there originally). So, it does not work on my macOS Docker installation (whether running directly from the Dockerhub image reference or from a copy of the repo built locally), but does on ist-aws-toolbox. That must mean there's something offensive on my local system.

**Comment by dsmk** [comment]
One other question:  Once this is merged into the master branch do you build the bostonuniversity/aws-tools image?  I don't believe that I have access to the bostonuniversity organization.

**Comment by bfenster** [comment]
> One other question: Once this is merged into the master branch do you build the bostonuniversity/aws-tools image? I don't believe that I have access to the bostonuniversity organization.

Yes, I'm pretty sure I did that last time. I can't think of any reason you shouldn't have access to the organization, but I don't have admin access, so I'll settle for just pushing the buttons myself.

**Comment by dsmk** [comment]
Ben, I just merged the changes.  Please let me know when you have built the image.

Is your Mac running the M1 processor?  Can you give your mac another try and let me know the time, date, and IP?  I'll look at the logs on the Shibboleth side to see if there's anything unusual.

Thanks,

**Comment by bfenster** [comment]
This is pushed to DockerHub as `bostonuniversity/aws-tools:0.3.0` and as `bostonuniversity/aws-tools:latest`

I'm on an Intel Mac, 161.97.243.109, and the last failure was about 2021-08-09 09:46 (Eastern). It doesn't sound likely that Shibboleth will have seen anything unusual; I think something in the "local" (in Docker) Chromium is failing, but I don't know how to get better visibility into that.

**Pull request merged**
